site_name: MGLFW
# site_url: https://skelebyte.github.io/mglfw_docs
theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - content.code.copy


nav:
  - Docs:
    - documentation/index.md
    - documentation/Getting Started/index.md

  - Blog:
    - blog/index.md



extra:
  social:
    - icon: custom/github
      link: https://github.com/Skelebyte
    - icon: custom/bluesky
      link: https://bsky.app/profile/skelebyte.bsky.social

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - blog